config/routes.rb
Rails.application.routes.draw do
  resources :products

  root 'products#index'
  post '/import', to: 'products#import', as: 'import_products'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  has_many :productspurchased, dependent: :delete_all
end

app/models/product.rb
class Product < ApplicationRecord
  require 'csv'

  has_many :productsseller, dependent: :delete_all
  has_many :productspurchased, dependent: :delete_all

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |name_buyer, description, price, total, address_seller, name_seller|
      buyer = Buyer.find_by_name(name_buyer[1])
      buyer = Buyer.create!(name: name_buyer[1]) if buyer.nil?

      product = Product.find_by_description(description[1])
      if product.nil?
        product = Product.create!(description: description[1], price: price[1], total: total[1])
      else
        product.update(total: (product.total + total[1].to_i))
      end

      productssellers = Productsseller.where(product_id: product.id)
      if productssellers.nil?
        seller = Seller.find_by_name(name_seller[1])
        seller = Seller.create!(name: name_seller[1], address: address_seller[1]) if seller.nil?
      else
        productssellers.each { |productsseller| seller = Seller.find_by_id(productsseller.seller_id) }
        if seller.nil?
          seller = Seller.create!(name: name_seller[1], address: address_seller[1])
          Productsseller.create!(seller_id: seller.id, product_id: product.id)
        end
      end

      Productspurchased.create!(buyer_id: buyer.id, product_id: product.id)
    end
  end
end

app/models/productspurchased.rb
class Productspurchased < ApplicationRecord
  belongs_to :buyer
  belongs_to :product
end

app/models/productsseller.rb
class Productsseller < ApplicationRecord
  belongs_to :seller
  belongs_to :product
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_many :productsseller, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[edit update destroy]
  before_action :set_product_seller_buyer, only: %i[show]

  def import
    Product.import(params[:file])
    redirect_to root_url, notice: 'Activity data imported!'
  end

  def index
    @products = Product.all
  end

  def show; end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def set_product_seller_buyer
    @product = Product.find(params[:id])
    @sellers = Productsseller.where(product_id: params[:id]).includes(:seller)
    @buyers = Productspurchased.where(product_id: params[:id]).includes(:buyer)
  end

  def product_params
    params.require(:product).permit(:description, :price, :total)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImportCsv</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.number_field :total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Price</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.total %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Description</th>
              <th>Price</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @product.description %></td>
              <td><%= @product.price %></td>
              <td><%= @product.total %></td>
              <td><%= link_to 'Edit', edit_product_path(@product) %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-6">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Address</th>
          </tr>
        </thead>
        <tbody>
          <% @sellers.each do |seller| %>
            <tr>
              <td><%= seller.seller.name %></td>
              <td><%= seller.seller.address %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
          <% @buyers.each do |buyer| %>
            <tr>
              <td><%= buyer.buyer.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<%= link_to 'Back', products_path %>
</div>